version: "3"
services:
  postgres:
    image: "postgres:alpine"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mqtt
    ports:
      - 6543:5432
    networks:
     - app-network
    restart: always
    volumes:
     - postgres-data:/home-sensors/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - NODE_ENV=production
      - MQTT_HOST=decentservice.xyz
    depends_on:
      - postgres
    ports:
      - 8070:3002
    networks:
     - app-network
    restart: always
networks:
 app-network:
volumes:
 postgres-data: