version: "3"
services:
  postgres:
    image: "postgres:alpine"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mqtt
    ports:
      - 5432:5432
